# Generated by Django 3.1.2 on 2020-10-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='post',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='post_stage',
        ),
    ]
