# Generated by Django 3.1.2 on 2020-10-26 12:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='developer',
            managers=[
                ('myManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(default='defaultPicture', upload_to='images/', verbose_name='Картинка'),
        ),
    ]
