# Generated by Django 3.1.2 on 2020-10-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201026_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(default='defaultPicture', height_field='100', upload_to='images/', verbose_name='Картинка', width_field='100'),
        ),
    ]
