# Generated by Django 3.1.2 on 2020-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201026_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(default='defaultPicture', height_field='image_height', upload_to='images/', verbose_name='Картинка', width_field='image_width'),
        ),
    ]
