# Generated by Django 3.1.2 on 2020-10-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201026_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='image',
        ),
    ]
